name: Tests

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.0

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.09"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.49.0
          cache: true
      - name: Install Python dev dependencies
        run: pixi run install-dev
      - name: Execute tests
        run: pixi run -e dev check-all
